# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ur5_arm_controller
    # - hand_controller

  ur5_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
  # hand_controller:
  #   type: FollowJointTrajectory
  #   action_ns: follow_joint_trajectory
  #   joints:
  #     - ur5_robotiq_85_left_knuckle_joint
