planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0
    longest_valid_segment_fraction: 0.005
    max_nearest_neighbors: 100

  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    longest_valid_segment_fraction: 0.005
    max_nearest_neighbors: 100
    goal_bias: 0.05
    delay_collision_checking: 1

  PRMstar:
    type: geometric::PRMstar
    range: 0.0
    max_nearest_neighbors: 100
    delay_collision_checking: 1

# You can add more planner configurations here
