planning_plugin: pilz_industrial_motion_planner/CommandPlanner

pilz_industrial_motion_planner:
  planning_plugin: pilz_industrial_motion_planner/CommandPlanner
  request_adapters:
    - default_planner_request_adapters/FixWorkspaceBounds
    - default_planner_request_adapters/FixStartStateBounds
    - default_planner_request_adapters/FixStartStateCollision
    - default_planner_request_adapters/FixStartStatePathConstraints
  start_state_max_bounds_error: 0.1

# Capabilities for Pilz planner
capabilities: pilz_industrial_motion_planner/MoveGroupSequenceAction pilz_industrial_motion_planner/MoveGroupSequenceService

# Default planner configuration
default_planner_config: PTP

