# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100

    ur5_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


ur5_arm_controller:
  ros__parameters:
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

hand_controller:
  ros__parameters:
    joints:
      - ur5_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
