controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Controller for the packing_arm_ UR5
    packing_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - packing_arm_shoulder_pan_joint
          - packing_arm_shoulder_lift_joint
          - packing_arm_elbow_joint
          - packing_arm_wrist_1_joint
          - packing_arm_wrist_2_joint
          - packing_arm_wrist_3_joint
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
          - effort

    # Controller for the cb_ UR5
    cb_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - cb_shoulder_pan_joint
          - cb_shoulder_lift_joint
          - cb_elbow_joint
          - cb_wrist_1_joint
          - cb_wrist_2_joint
          - cb_wrist_3_joint
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
          - effort

    # Controller for the Robotiq Gripper on packing_arm_
    packing_arm_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - packing_arm_robotiq_85_left_knuckle_joint
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
          - effort

    # Controller for the Cardboard Gripper on cb_
    cb_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - cb_gripper_base_to_finger
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
          - effort
